name: Render HTML
on: [push]
jobs:
  html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: "pip install -r requirements.txt"
      - name: Sphinx build
        run: 'sphinx-build -M html "source" "build"'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
          force_orphan: true
