name: Sync source from spreadsheet
on:
  workflow_dispatch:
  schedule:
    - cron: '30 12 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: "pip install -r requirements.txt"
      - name: Set GCP service account
        run: 'mkdir -p ~/.config/gspread && echo "$GCP_SERVICE_ACCOUNT" > ~/.config/gspread/service_account.json'
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Sync .rst files
        run: "python bookshelf.py --fetch --render"
      - name: Sphinx build
        run: 'sphinx-build -M html "source" "build"'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
          force_orphan: true
